### ISSUE TITLE
Bug with prebuilding a target from imported file

### ISSUE THREAD

**Issue by nsheff** [databio/markmeld#21]
If you try to put a target from an imported file (or a non-existant target) into `prebuild`, you get this error:

```
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/mm", line 8, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.8/site-packages/markmeld/cli.py", line 213, in main
    report_result(built_target)
  File "/home/nsheff/.local/lib/python3.8/site-packages/markmeld/cli.py", line 187, in report_result
    if "output_file" in built_target.meta and built_target.meta["output_file"]:
AttributeError: 'bool' object has no attribute 'meta'

```

Instead:
- [x] a prebuild that doesn't exist should state so
- [x] a prebuild that exists in an imported file should be allowed, and should work.

**Comment by nsheff** [comment]
This works in version 0.3
